import type { Edge, Node } from '@xyflow/react';

import {
  countEndpointNodeTraversalHits,
  countUnrelatedObstacleHits,
} from '../../strategies/shared/edgeWaypointCandidateRepair';
import {
  buildDisplayRoutingObstacles,
  displayRoutingObstaclesSignature,
  type DisplayPoint,
  type DisplayRect,
} from './baseReactFlowDisplayGeometry';

const MAX_CACHED_PATHS_PER_NODE_SNAPSHOT = 4096;

type CachedPathObstacleHits = {
  unrelated?: number;
  endpoint?: number;
};

export type DisplayObstacleHitContext = {
  nodeSignature: string;
  obstacles: Map<string, DisplayRect>;
  countUnrelated: (path: DisplayPoint[], edge: Edge) => number;
  countRouting: (path: DisplayPoint[], edge: Edge) => number;
  countEdgesUnrelated: (edges: Edge[], pathForEdge: (edge: Edge) => DisplayPoint[]) => number;
};

const displayCoordinateToken = (value: number): string => {
  if (Number.isNaN(value)) return 'nan';
  if (value === Number.POSITIVE_INFINITY) return '+infinity';
  if (value === Number.NEGATIVE_INFINITY) return '-infinity';
  if (Object.is(value, -0)) return '-0';
  return String(value);
};

const displayObstaclePathKey = (path: DisplayPoint[], edge: Edge): string => JSON.stringify([
  edge.source,
  edge.target,
  path.map(point => [displayCoordinateToken(point.x), displayCoordinateToken(point.y)]),
]);

const cacheBoundedPathResult = (
  cache: Map<string, CachedPathObstacleHits>,
  key: string,
  value: CachedPathObstacleHits,
): CachedPathObstacleHits => {
  if (!cache.has(key) && cache.size >= MAX_CACHED_PATHS_PER_NODE_SNAPSHOT) {
    const oldestKey = cache.keys().next().value as string | undefined;
    if (oldestKey !== undefined) cache.delete(oldestKey);
  }
  cache.set(key, value);
  return value;
};

const displayObstacleHitContextCache = new WeakMap<Node[], {
  nodeSignature: string;
  context: DisplayObstacleHitContext;
}>();

/**
 * Reuses exact obstacle-hit results for candidate paths generated by repeated
 * display-routing stages. The weak node-array key avoids retaining old graphs;
 * the full node-geometry signature invalidates in-place layout mutations; and
 * the per-snapshot FIFO bound prevents candidate enumeration from growing the
 * cache without limit.
 */
export const createDisplayObstacleHitContext = (nodes: Node[]): DisplayObstacleHitContext => {
  const nodeSignature = displayRoutingObstaclesSignature(nodes);
  const cached = displayObstacleHitContextCache.get(nodes);
  if (cached?.nodeSignature === nodeSignature) return cached.context;

  const obstacles = buildDisplayRoutingObstacles(nodes);
  const pathHits = new Map<string, CachedPathObstacleHits>();
  const entryFor = (path: DisplayPoint[], edge: Edge): [string, CachedPathObstacleHits] => {
    const key = displayObstaclePathKey(path, edge);
    return [key, pathHits.get(key) ?? {}];
  };
  const countUnrelated = (path: DisplayPoint[], edge: Edge): number => {
    if (path.length < 2 || obstacles.size === 0) return 0;
    const [key, entry] = entryFor(path, edge);
    if (entry.unrelated !== undefined) return entry.unrelated;
    const unrelated = countUnrelatedObstacleHits(path, edge, obstacles);
    cacheBoundedPathResult(pathHits, key, { ...entry, unrelated });
    return unrelated;
  };
  const countRouting = (path: DisplayPoint[], edge: Edge): number => {
    if (path.length < 2 || obstacles.size === 0) return 0;
    const [key, entry] = entryFor(path, edge);
    const unrelated = entry.unrelated
      ?? countUnrelatedObstacleHits(path, edge, obstacles);
    const endpoint = entry.endpoint
      ?? countEndpointNodeTraversalHits(path, edge, obstacles);
    if (entry.unrelated === undefined || entry.endpoint === undefined) {
      cacheBoundedPathResult(pathHits, key, { unrelated, endpoint });
    }
    return unrelated + endpoint;
  };
  const context: DisplayObstacleHitContext = {
    nodeSignature,
    obstacles,
    countUnrelated,
    countRouting,
    countEdgesUnrelated: (edges, pathForEdge) => edges.reduce((total, edge) => (
      total + countUnrelated(pathForEdge(edge), edge)
    ), 0),
  };
  displayObstacleHitContextCache.set(nodes, { nodeSignature, context });
  return context;
};
